service: pedirPizzas

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  hacerPedido:
    handler: handler.hacerPedido
    events:
      -http:
        method: POST
        path: pedido
